### ISSUE TITLE
Missing Dependencies in README and Missing build targets in CMakeLists.txt

### ISSUE THREAD

**Issue by leaf0917** [fwilliams/surface-reconstruction-benchmark#2]
I follow your instructions when I execute **_cmake .. -DCMAKE_BUILD_TYPE=Release_**. There are the following mistakes. How can I solve them? Thank you.

-- Could NOT find OpenEXR (missing: ILMBASE_INCLUDE_PATH OPENEXR_INCLUDE_PATH OPENEXR_IMATH_LIBRARY OPENEXR_ILMIMF_LIBRARY OPENEXR_IEX_LIBRARY OPENEXR_HALF_LIBRARY) (found version "1.6.1")
-- Could NOT find TIFF (missing: TIFF_LIBRARY TIFF_INCLUDE_DIR) 
CMake Error at pbrt/CMakeLists.txt:19 (message):
  OPENEXR_FOUND

-- Configuring incomplete, errors occurred!

**Comment by fwilliams** [comment]
This error appears is because you don't have OpenEXR and libTiff install on your system which is a dependency for the library. If you search for these for your distribution, they should be available.

I'll add these to the list of dependencies.

**Comment by fwilliams** [comment]
Can you also tell me what platform you're trying to build on?

**Comment by leaf0917** [comment]
I'm sorry to reply to you late because of time difference, my platform is _Ubuntu 18.04.5 LTS_.

**Comment by fwilliams** [comment]
Did you try installing the additional dependencies? I updated the README to reflect these. It seems you're missing OpenEXR and libtiff.

**Comment by leaf0917** [comment]
I installed these libraries and compiled, but I'm not sure if it was successful because I didn't find the executable files in the **_./bin_** directory, but found it in the **_bulid_** directory, such as **_implicit_uniform_**, but **_mesh_to_implicit_** and **_isosurface_** are not found.

**Comment by fwilliams** [comment]
Ah this is a typo in the README. Cmake will output build artifacts in the directory where you launched it by default. So these binaries should be in `build`. I'll update the readme and close the issue. Let me know if there are any other problems and I'll reopen it.

**Comment by leaf0917** [comment]
Another problem is that I can not find **_mesh_to_implicit_** and **_isosurface_**, did you rename them

**Comment by fwilliams** [comment]
It looks like there's no target for these binaries in the CMakeLists. I haven't used this repo to scan any new meshes and just used the ones from the benchmark. Could you add these build targets and send a PR? I'd appreciate it a lot!

**Comment by leaf0917** [comment]
I will try

**Comment by fwilliams** [comment]
@leaf0917 Turns out this was a very small 6 line fix to the CMakeLists.txt. If you grab the latest version, cmake should build these binaries for you.

**Comment by leaf0917** [comment]
Thank you. I finally compiled it. But when I execute the example **_python scripts/RunSampler.py data/pcs/bumps/bumps_0.cnf_**,  the following error occurs:
_['./bin/uniform_sampler', 'modeling/models/bumps/bumps.mpu', 'data/pcs/bumps/bumps_0.npts', '50', '50', '9', 'min_range', '70.0000000', 'registration_error', '0.4000000', 'normal_type', '2']
Traceback (most recent call last):
  File "scripts/RunSampler.py", line 132, in <module>
    runUniform(config, pathdir, infile, outfile)
  File "scripts/RunSampler.py", line 115, in runUniform
    runcommand(args)
  File "scripts/RunSampler.py", line 45, in runcommand
    raise RunError(args[0] + ': Fork falied with error \'' + e.strerror + '\'')
__ main __ .RunError: Error: ./bin/uniform_sampler: Fork falied with error 'No such file or directory'_

**Comment by fwilliams** [comment]
Hi @leaf0917 it seems that a file is missing somewhere. 

This repository is just a copy of the original codebase from Berger et.al and I don't know all its internals well. Unfortunately, I don't have time to debug this beyond ensuring that it builds. Given that the error seems to be in a Python script and you get a stack trace, it should be doable to fix it. If you do find any bugs, please send a pull request with your fixes.

Thanks!

**Comment by leaf0917** [comment]
I will try to fix it, thank you so much!

**Comment by HeCraneChen** [comment]
Hi, thanks for the code! But I can't find **pc_generator** after executing "make". I only have the following .o files. Did you rename pc_generator to something else?
[  9%] Built target trimesh2
[ 13%] Built target tps
[ 17%] Built target ann
[ 26%] Built target OpenMesh
[ 57%] Built target pbrt
[ 62%] Built target Sampler
[ 64%] Built target Modeling
[ 67%] Built target sample_implicit
[ 70%] Built target single_distribution
[ 73%] Built target dump_single
[ 76%] Built target implicit_uniform
[ 76%] Built target isosurface
[ 76%] Built target mesh_to_implicit
[ 79%] Built target dump_barplot
[ 82%] Built target run_evaluation
[ 85%] Built target dump_meta
[ 87%] Built target sample_mesh
[ 89%] Built target aggregate_distribution
[ 92%] Built target mesh_fixer
[ 95%] Built target dump_distribution
[ 98%] Built target aggregation
[100%] Built target dump_lines
[100%] Built target ann_exec

**Comment by fwilliams** [comment]
@HeCraneChen looks like there's just no build target in the `CMakeLists.txt`. This repository came to being for a particular project a few years ago and we only added targets for the binaries we needed then, so it's likely there are missing targets. Could you add one for `pc_generator` and send a pull request?

**Comment by HeCraneChen** [comment]
Pull request sent! That's also what I figured. I also added uniform_sampler to CMakeLists.txt. I hope I understood it correctly. Otherwise, it's going to complain no bin/uniform_sampler when running "**python scripts/RunSampler.py config_file**" . But there's still another problem when running this. I got "ERROR: uniform sampling not at prescribed size!" message from line 147 of _UniformSampler.cpp_. I figured this bug came from _ImplicitSphere.h_, where the code is trying to read "_sphere_sampled.npts_"? But we don't have any npts file to read yet, right? The goal of this python script is to generate one npts file from the config file.
